#!/usr/bin/with-contenv sh

cd /

echo "=== PYTHON TEST ==="

python3 <<'PY'
import traceback

try:
    import app
    print("APP IMPORT OK")
except Exception:
    traceback.print_exc()
    raise
PY

exec python3 -m uvicorn app:app --host 0.0.0.0 --port 8099
